# Generated by Django 4.1.5 on 2023-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='catalog/')),
                ('text1', models.TextField(verbose_name='Анонс')),
                ('fultext', models.TextField(verbose_name='Статья')),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='SME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('imageS', models.ImageField(blank=True, upload_to='catalog/')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('data1', models.DateField()),
                ('ss', models.TextField(max_length=450, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'СМИ',
                'verbose_name_plural': 'СМИ',
            },
        ),
    ]
