# Generated by Django 4.1.5 on 2023-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sme',
            name='ss',
            field=models.TextField(default='', max_length=450, verbose_name='Ссылка'),
        ),
    ]
