# Generated by Django 4.1.5 on 2023-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text1',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
